export const AnalyticsReportContent = {
  SelectedVersion: 'Selected version',
  ActiveVersion: 'Active version',
  Publication: 'Publication / rollback',
  PublicationCount: 'Changes: {count}',
  Rate: 'Recommendation-open rate',
  Date: 'Cohort date',
  ViewData: 'View chart data',
  ClearSegments: 'Clear acquisition filters',
  Traffic: 'Traffic origin',
  Production: 'Production',
  Synthetic: 'Synthetic',
  AllTraffic: 'All traffic',
  Forced: 'Include forced assignments',
  Truncated: 'Only the first returned groups are shown. Narrow the report to inspect more.',
  TransitionRate: 'Continued among observed source sessions: {numerator} / {denominator}',
  DestinationMissing: 'Transition without a destination view: {open} open · {expired} expired',
  FullHistory:
    'Full recorded session history; the report period selects sessions by their start date.',
  Incoming: 'Incoming transitions',
  Outgoing: 'Outgoing transitions',
  Duration: 'Mean observed step duration',
  DurationExplanation:
    'Seconds from a recorded view to completion; only paired observations contribute.',
  Sessions: 'Session timeline',
  TimelineExplanation: 'Recorded events only. No answers or participant access tokens are exposed.',
  PreviousSessions: 'Previous sessions',
  More: 'Load more sessions',
  EventsTruncated: 'This timeline is truncated.',
  NoTransitions: 'No recorded transitions in this selection.',
  NoSessions: 'No recorded sessions match this step and report.',
  Event: 'Event',
  Timestamp: 'Time',
  Variant: 'Variant',
  Inspect: 'Inspect',
  Seconds: '{seconds} seconds · {count} paired observations',
  QualitySummary: '{mature} mature sessions · {open} sessions still open',
  ConversionWindowPending: 'Waiting for outcomes',
  Period: 'Period',
  Today: 'Today',
  LastSeven: 'Last 7 days',
  LastThirty: 'Last 30 days',
  Custom: 'Custom period',
  From: 'Start date',
  Through: 'End date',
  Timezone: 'Report timezone',
  Window: 'Conversion window',
  Hours: '{hours} hours',
  Apply: 'Apply period',
  PendingPeriod: 'Period changed. Apply it to update the report, links and export.',
  PeriodExplanation:
    'Sessions are grouped by their start date. Outcomes count only within the conversion window, up to the report time.',
  InvalidPeriod: 'Choose a valid date range of no more than 366 days and a supported timezone.',
  Save: 'Save report',
  Saved: 'Saved reports',
  Name: 'Report name',
  LocalReports: 'Saved in this browser only. Shared links contain filters, not access to the data.',
  CopyLink: 'Copy report link',
  LinkCopied: 'Report link copied.',
  CopyFailed: 'The link could not be copied. Copy it from the address bar.',
  StorageFailed: 'The report could not be saved in this browser.',
  ReportSaved: 'Report saved in this browser.',
  Export: 'Export aggregates',
  ExportDescription: 'CSV uses the exact report filters and contains aggregates only.',
  Started: 'Started sessions',
  SelectedCohort: 'Sessions matching the report filters',
  Results: 'Viewed a result',
  Opens: 'Opened recommendations',
  Engagement: 'Recommendation opens measure engagement, not leads or sales.',
  Sample: '{numerator} of {denominator} sessions',
  Observed: 'Observed values; not a confirmed experiment result.',
  NoComparison: 'No comparable sessions in the previous period.',
  Previous: 'Previous period',
  Difference: '{difference} PP versus previous period',
  Quality: 'Data quality',
  LastEvent: 'Latest received event',
  NoEvents: 'No events received for this selection.',
  MissingViews: '{count} completions without a recorded view',
  MissingDescription:
    'Server-confirmed completion and browser views are separate signals. Missing views are not treated as zero engagement.',
  StillObserving:
    'Some sessions are still inside the conversion window. Their outcomes may change.',
  TestTraffic: 'Test traffic is included. Do not use it to choose an experiment winner.',
  Trend: 'Conversion over time',
  TrendDescription:
    'Daily cohorts by session start. Publication markers indicate configuration changes, not evidence of their effect.',
  Segment: 'Acquisition segments',
  Source: 'Source',
  Medium: 'Medium',
  Campaign: 'Campaign',
  All: 'All values',
  Unattributed: 'Not recorded',
  SegmentsDescription:
    'Compare volume and recommendation-open rate. A change in traffic mix can change the overall rate.',
  SelectSegment: 'Filter to this segment',
  ResultsDistribution: 'Result distribution',
  Result: 'Result',
  NoResult: 'No result views in this selection.',
  Steps: 'Steps and diagnostics',
  Step: 'Step',
  Views: 'Viewed',
  Completed: 'Completed',
  Open: 'Open',
  Expired: 'Expired',
  Missing: 'Missing views',
  Diagnose: 'Inspect step',
  StepsDescription:
    'Reach is not a sequential drop-off funnel. Conditional branches may skip steps; counts represent sessions, not unique people.',
  NoTraffic: 'No started sessions in this selection.',
  NoTrafficHelp:
    'Check the period, active version and acquisition filters. No traffic alone does not prove tracking is broken.',
  Loading: 'Loading report',
  Unavailable: 'The report could not be loaded.',
  Retry: 'Try again',
  Experiment: 'Experiment decision',
  Exploration: 'Exploratory comparison',
  Insufficient: 'Not enough evidence to choose a winner',
  Business: 'Business outcomes',
  BusinessDescription:
    'Only recorded outcomes appear here. A recommendation open is not a lead, qualification or purchase.',
  Lead: 'Lead',
  Qualified: 'Qualified lead',
  Purchase: 'Purchase',
  NotConnected:
    'No external CRM connection is configured by this application. Server-reported and manually recorded outcomes are identified separately.',
} as const;
