export const AnalyticsContent = {
  StepReach: 'Step reach',
  Variant: 'Variant',
  StartedBranchDescription:
    'started sessions. Branches may skip steps, so this is not a sequential drop-off funnel.',
  StepsUnit: 'steps',
  ConditionalStepsUnit: 'conditional steps',
  RecordedReach: 'Reach based on recorded views',
  EmptyReach:
    'No sessions started with these filters. Reach percentages will appear when traffic arrives.',
  UnobservedCompletions: 'Some completions have no recorded view.',
  ReachEvidence:
    'Reach uses browser view events; completion uses server-confirmed progress. Missing view events can make reach lower than completion.',
  ReachCaption: 'Step reach and completion for variant',
  Step: 'Step',
  Reached: 'Reached',
  ViewsShare: 'Views · % of starts',
  Completed: 'Completed',
  ConfirmedProgress: 'Confirmed progress',
  Open: 'Open',
  MayContinue: 'May still continue',
  Expired: 'Expired',
  WithoutCompletion: 'Without completion',
  Conditional: 'Conditional',
  StepReachLabel: '{step}: share of started sessions reached',
  EmptySteps: 'No step data is available for this variant.',
  MetricHelp: 'How to read these metrics',
  ReachDefinitionTitle: 'Reach.',
  ReachDefinition:
    'Sessions with a recorded step view, as a share of all started sessions in this variant. Conditional branches can skip steps.',
  CompletionDefinitionTitle: 'Completed.',
  CompletionDefinition:
    'Sessions with server-confirmed progress past the step. Completion does not apply to result steps.',
  OpenDefinitionTitle: 'Open.',
  OpenDefinition: 'Sessions that reached the step without completing it and may still continue.',
  ExpiredDefinitionTitle: 'Expired.',
  ExpiredDefinition:
    'Sessions that reached the step and expired without completion. Counts are per step, not unique lost sessions.',
  ResultCompletion: 'Result completion',
  CallToActionConversion: 'CTA conversion',
  VariantLabel: 'Variant {variant}',
  FiltersTitle: 'Analytics filters',
  FiltersDescription: 'Choose which sessions to include in this report.',
  QuickPresets: 'Quick presets',
  QuickPresetsTitle: 'Quick presets · traffic & assignment',
  Production: 'Production',
  TestTraffic: 'Test traffic',
  Everything: 'Everything',
  PresetDescription: 'Presets keep your campaign selection.',
  Campaign: 'Campaign',
  AllCampaigns: 'All campaigns',
  SpecificCampaign: 'Specific campaign',
  NoCampaign: 'No campaign',
  CampaignDescription:
    'Filter by the session’s utm_campaign value. “No campaign” includes sessions without this value.',
  CampaignName: 'Campaign name',
  CampaignPlaceholder: 'e.g. demo-google-search',
  CampaignExactValue: 'Use the exact value, including letter case.',
  Sessions: 'Sessions',
  TrafficOrigin: 'Traffic origin',
  Synthetic: 'Synthetic',
  AllTraffic: 'All traffic',
  All: 'All',
  ProductionDescription: 'Only sessions marked as production.',
  TestTrafficDescription:
    'Includes synthetic test sessions. Use this view to inspect tracking, not to pick a winning variant.',
  ForcedAssignments: 'Forced assignments',
  Exclude: 'Exclude',
  Include: 'Include',
  ForcedAssignmentsDescription:
    'Forced sessions select A or B explicitly instead of using random assignment. Exclude them for experiment comparisons.',
  SelectedFilters: 'Selected filters',
  ReportSelection: 'Report selection',
  ForcedIncluded: 'Forced assignments included',
  RandomOnly: 'Random assignments only',
  ApplyDescription: 'The report updates when you apply. Your selected version stays the same.',
  Reset: 'Reset',
  Cancel: 'Cancel',
  ApplyFilters: 'Apply filters',
  SyntheticTraffic: 'Synthetic traffic',
  ProductionTraffic: 'Production traffic',
  CampaignLabel: 'Campaign: {campaign}',
  EmptyCampaign: '(empty)',
  VersionLabel: 'Version {version}',
  ChooseVersionLabel: 'Choose version: {version}',
  ChooseVersion: 'Choose configuration version',
  SearchVersions: 'Search all versions',
  SearchPlaceholder: 'Version number, schema or checksum…',
  Page: 'Page',
  UpTo: '· up to',
  GlobalSearchScope: 'versions per page. Search covers all versions.',
  LoadingVersions: 'Loading versions…',
  Retry: 'Retry',
  TryAgain: 'Try again',
  EmptyVersionSearch: 'No versions match this search. Try a different value or clear the search.',
  Version: 'Version',
  Previous: 'Previous',
  Next: 'Next',
  NotAvailable: 'Not available',
  StepsSeparator: 'steps ·',
  TransitionsUnit: 'transitions',
  PrimaryConversion: 'CTA conversion · primary',
  VariantConversionLabel: 'Variant {variant} CTA conversion',
  Started: 'Started',
  SessionsUnit: 'sessions',
  CallToActionClickThrough: 'CTA click-through',
  VariantSteps: '· steps',
  StepsDescription: 'See how many sessions reached each step and continued to the next one.',
  StepsCaption:
    'Open sessions can still continue. Expired dropout is the share of expired viewers who did not complete the step. Results are the final step, so only views are counted.',
  Completion: 'Completion',
  ExpiredDropout: 'Expired dropout',
  TerminalReach: 'Terminal · reach only',
  StepCompletionLabel: '{step} completion',
  VariantTransitions: '· transitions',
  PathsDescription:
    'Follow sessions between steps. Sessions sent to another branch aren’t counted as missing the destination.',
  PathsCaption:
    'Observed conversion: source viewers reaching this destination. Branch share: transitions on this edge / source forward transitions. Transition-to-view: destination viewers / edge transitions. Branch shares may exceed 100% in total after revisits.',
  Path: 'Path',
  Transitions: 'Transitions',
  ObservedConversion: 'Observed conversion',
  BranchShare: 'Branch share',
  TransitionToView: 'Transition-to-view',
  DestinationPending: 'Destination pending',
  DestinationExpired: 'Destination expired',
  EmptyPaths: 'No paths recorded yet',
  EmptyPathsDescription: 'Paths appear after a session moves forward between steps.',
  VersionAnalyticsLabel: 'Version {version} analytics',
  ConversionByVariant: 'Conversion by variant',
  ConversionDescription: 'Result views and recorded CTA clicks per started session.',
  EmptySessions: 'No sessions yet',
  EmptySessionsDescription:
    'No sessions match these filters. Try another filter or check back after the funnel receives traffic.',
  AdjustFilters: 'Adjust filters',
  SessionSplit: 'Session split',
  StartedSessions: 'Started sessions',
  VariantStartsLabel: 'Variant {variant} share of started sessions',
  RateDenominatorDescription:
    'Both chart rates use started sessions. CTA click-through uses only sessions that viewed a result.',
  StepResults: 'Step-by-step results',
  StepResultsDescription: 'Choose a variant to review its steps and paths.',
  VersionVariantsLabel: 'Version {version} variants',
  VariantDetailsLabel: 'Variant {variant} detail views',
  Steps: 'Steps',
  Paths: 'Paths',
  RevisitDescription:
    'Sessions can go back or switch branches, so counts may rise between steps. Only events received by the server are included.',
  ResultToActionUnit: 'result → CTA',
  EmptyVariant: 'No started sessions for this variant.',
  ComparisonDirection: 'B vs A',
  ComparisonSignificance: 'Percentage points · significance not tested',
  StartsShare: 'of starts',
  VariantShareLabel: 'Variant {variant}: share of starts',
  VariantMetricLabel: 'Variant {variant}: {metric}',
  MarketingOverview: 'Marketing performance overview',
  AcrossVariants: '· Across selected variants',
  ObservedSplit: 'Observed session split',
  FilterCounts: 'Counts follow the current traffic and campaign filters.',
  Of: 'of',
  StartsViewedResult: 'starts viewed a result',
  StartsClickedAction: 'starts clicked a CTA',
  SessionMilestones: 'Session milestones',
  RibbonDescription: 'Ribbon width shows session count on a shared scale.',
  ResultViewed: 'Result viewed',
  ResultViewersClicked: 'Result viewers who clicked',
  EmptyMilestones: 'Your funnel will appear here',
  EmptyMilestonesDescription:
    'No started sessions match the current filters. Milestones appear when traffic reaches this version.',
  MilestonesDescription:
    'Milestones across all branches. Sessions without a result may still be open.',
  MilestonesCaption: 'Session milestone counts by variant',
  VariantComparison: 'Variant comparison',
  ConversionDifference: 'CTA conversion · B minus A',
  EmptyComparison: 'No comparison yet',
  EmptyComparisonDescription: 'Both variants need sessions to compare CTA conversion.',
  DifferenceDescription: 'Percentage-point difference. Statistical significance is not tested.',
  ResultToAction: 'Result → CTA',
  ClickThroughDescription: 'CTA clicks / result views, across selected variants.',
  LatestVersion: 'Latest version',
  ForcedExcluded: 'Forced assignments excluded',
  Filters: 'Filters',
  Refresh: 'Refresh',
  TestTrafficWarning:
    'Includes test sessions. Don’t use these results to choose a winning variant.',
  Updated: 'Updated',
  LoadingAnalytics: 'Loading analytics',
  AnalyticsUnavailable: 'Analytics could not be loaded',
  EmptyVersions: 'No matching versions',
  EmptyVersionsDescription:
    'Change the version or campaign filter. If this funnel is new, import a configuration first.',
  MetricDefinitions: 'Metric definitions',
  ConversionDefinition:
    'CTA conversion is the share of started sessions with a recorded CTA click. Result completion is the share that viewed a result. CTA click-through is the share of result viewers who also clicked a CTA.',
  ComparisonDefinition:
    'Compare variants within the same version and experiment. The configuration defines what differs between them. Differences across versions do not establish an experiment’s effect.',
  FilterDefinition:
    'All counts and rates use the selected filters. Campaigns come from the UTM value recorded at session start. Repeat views count once per session. Exclude forced assignments when comparing A and B.',
  NotApplicable: 'Not applicable',
  AllVersions: 'All versions',
  Information: 'Information',
  SingleChoice: 'Single choice',
  MultipleChoice: 'Multiple choice',
  NumberInput: 'Number input',
  Result: 'Result',
  ComparisonNeedsSessions: 'A/B comparison needs sessions in both variants.',

  versionLabel(version: number): string {
    return `Version ${version}`;
  },
} as const;
