export const QuizContent = {
  Actions: {
    Back: 'Back',
    Continue: 'Continue',
    Retry: 'Try again',
    RefreshSession: 'Refresh session',
    RetryDelivery: 'Retry delivery',
    Print: 'Print',
  },
  Shell: {
    Preview: 'Administrator preview · synthetic traffic. Your normal session is unchanged.',
    PreviewUnavailable: 'This preview is no longer available',
    PreviewRecovery:
      'Return to the configuration in administration and choose Test this version to create a new preview. Then reopen it from administration. Your normal quiz session is unchanged.',
    Skip: 'Skip to assessment',
    Home: 'Kelpie workstyle home',
    Context: 'Workstyle check',
    About: 'How it works',
    Disclaimer: 'This assessment uses demonstration content, not professional advice.',
    AboutTitle: 'A little reflection. A clearer direction.',
    AboutDescription:
      'Answer a few questions about your team. Your answers shape the route and the final recommendation. You can go back to make changes; a new answer is confirmed only with Continue.',
    AboutPersistence:
      'Your unfinished inputs are kept in this browser. The session is tied to the same configuration and variant throughout.',
    Footer: 'Thoughtful questions. Practical direction.',
    Assessment: 'Workstyle assessment',
    Loading: 'Getting everything ready…',
    Recovery: 'Let’s get you back on track.',
    Expired: 'Your previous session has expired. Start again for a fresh recommendation.',
  },
  Welcome: {
    Eyebrow: 'GOOD WORK STARTS WITH YOUR PEOPLE',
    TeamHeadline: 'Your team.',
    WorkHeadline: 'A better way',
    WorkEmphasis: 'to work.',
    Description:
      'Find a work model that fits the way your team actually works. A few thoughtful questions. One practical direction.',
    Starting: 'Getting ready…',
    Start: 'Find your workstyle',
    NoAccount: 'No account needed',
    Pace: 'Go at your own pace',
    TeamTitle: 'Your team',
    TeamDescription: 'Tell us how you work today.',
    PrioritiesTitle: 'Your priorities',
    PrioritiesDescription: 'Reflect on what matters most.',
    DirectionTitle: 'Your direction',
    DirectionDescription: 'Leave with a practical next step.',
  },
  Question: {
    Ready: 'Your recommendation is ready',
    ProgressLabel: 'Questions complete',
    ContextEyebrow: 'THE WORKSTYLE CHECK',
    ContextTitle: 'A little context.',
    ContextEmphasis: 'A clearer picture.',
    ContextDescription:
      'Think about your team as it is today, rather than how you’d like it to be.',
    ReviewReminder: 'You can review your answers before you’re done.',
    BrandLine: 'Made for the way',
    BrandEmphasis: 'you work.',
    InteractiveEyebrow: 'LET’S UNDERSTAND YOUR TEAM',
    InformationEyebrow: 'A BETTER WAY TO WORK',
    Selected: 'selected',
    Help: 'Choose the answer that feels closest to your team today.',
    Saving: 'Saving…',
    Confirmation: 'Answers are confirmed only when you continue.',
    Shortcut: 'Press',
  },
  Input: {
    Answer: 'Your answer',
    Decrease: 'Decrease answer',
    Increase: 'Increase answer',
    Adjust: 'Adjust answer',
  },
  Result: {
    Eyebrow: 'YOUR TEAM’S NEXT CHAPTER',
    Reassurance: 'Small changes. A practical place to start.',
    ActionsTitle: 'Your action list',
    Disclaimer:
      'A fictional recommendation for this assessment. Use it as a conversation starter with your team.',
    Review: 'Review your answers',
  },
  NotFound: {
    Title: 'Page not found',
    Description: 'This link does not lead to an assessment page.',
    Return: 'Return to assessment',
  },
  Illustration: {
    Description: 'From your team’s answers to a practical workstyle recommendation',
    BuiltAround: 'Built around',
    People: 'your people.',
    Eyebrow: 'A LITTLE CLARITY',
    Working: 'Your way of working.',
    Together: 'How you work together',
    Change: 'What needs to change',
    Start: 'Where to start',
    NextStep: 'THE NEXT STEP',
    Plan: 'A plan that fits.',
    StampTitle: 'LESS GUESSWORK',
    StampEmphasis: 'more direction',
  },
} as const;
