// Shared allowlists must not change between configuration validations at runtime.
export const EventPolicy = {
  Properties: Object.freeze([
    'step_type',
    'visible_step_index',
    'visible_step_count',
    'answer_kind',
    'next_step_id',
    'destination_step_id',
    'result_id',
    'action',
    'source',
  ]),
  BaseProperties: Object.freeze([
    'event_id',
    'session_id',
    'client_timestamp',
    'server_timestamp',
    'funnel_id',
    'funnel_version',
    'experiment_id',
    'variant',
    'step_id',
    'utm_source',
    'utm_medium',
    'utm_campaign',
  ]),
  RequiredEvents: Object.freeze([
    'session_started',
    'step_viewed',
    'answer_submitted',
    'step_completed',
    'back_clicked',
    'result_viewed',
    'cta_clicked',
  ]),
} as const;
