export const ConfigurationInspectionContent = {
  Funnel: 'Funnel',
  Locale: 'Locale',
  Schema: 'Schema',
  DocumentStatus: 'Document status',
  InspectStep: 'Inspect step',
  ConfigurationSteps: 'Configuration steps',
  Steps: 'Steps',
  VariantSeparator: '· Variant',
  If: 'If',
  Experiment: 'Experiment',
  ConfiguredTrafficAllocation: 'Configured traffic allocation',
  TrafficAllocation: 'Traffic allocation',
  TrafficAllocationDescription: 'Configured weights · actual traffic may vary',
  Variant: 'Variant',
  StepCountSuffix: 'steps',
  Assignment: 'Assignment',
  AssignmentDescription: 'The server assigns a variant when a session starts.',
  StickyVariant: 'Sticky variant',
  Enabled: 'Enabled',
  Disabled: 'Disabled',
  StickyVariantDescription: 'The assigned variant stays with the session.',
  OverrideQueryParameter: 'Override query parameter',
  OverrideParameterDescription: 'Request A or B explicitly with this query parameter.',
  Traffic: 'traffic',
  StepsWeight: 'steps · Weight',
  StepOrder: 'Step order',
  PositionComparisonDescription: 'Position changes are shown relative to variant',
  ResultSelection: 'Result selection',
  ResultSelectionDescription:
    'Rules are evaluated in order. The first matching rule selects the result; otherwise the default applies.',
  Rule: 'Rule',
  ShowResult: 'Show result',
  OtherwiseShow: 'Otherwise show',
  ConfiguredResults: 'Configured results',
  ResultContent: 'Result content',
  PreviewForVariant: 'Preview for variant',
  IncludesContentOverrides: '· Includes content overrides',
  DefaultResult: 'Default result',
  Override: 'override',
  Recommendations: 'Recommendations',
  PrimaryActionPreview: 'Primary action · Preview',
  Action: 'Action:',
  AnalyticsPrivacy: 'Analytics privacy',
  AnalyticsPrivacyDescription: 'What this configuration allows in analytics events.',
  RawAnswers: 'Raw answers',
  Stored: 'Stored',
  NotStored: 'Not stored',
  AnswerTypes: 'Answer types',
  Allowed: 'Allowed',
  Excluded: 'Excluded',
  SessionStorageDescription: 'Session answer storage is configured separately in Settings.',
  ViewDeclaration: 'View declaration',
  SharedProperties: 'Shared properties',
  SharedPropertiesDescription: 'Declared for every event below.',
  EventCatalog: 'Event catalog',
  EventCatalogDescription:
    'Configured triggers and additional properties. These describe events, not live activity.',
  AdditionalProperties: 'Additional properties',
  SharedPropertiesOnly: 'Shared properties only',
  VersionInformation: 'Version information',
  Description: 'Description',
  WhatChanged: 'What changed',
  Preview: 'Preview',
  VariantA: 'Variant A',
  VariantB: 'Variant B',
  Variants: 'Variants',
  Results: 'Results',
  Events: 'Events',
  Settings: 'Settings',
  Session: 'Session',
  SessionSettingsDescription: 'Lifetime, persistence and version pinning.',
  Progress: 'Progress',
  ProgressSettingsDescription: 'Visible steps and excluded step types.',
  OriginalConfiguration: 'Original configuration',
  OriginalConfigurationDescription:
    'The persisted document, formatted for reading. Variant overrides are not merged into this view.',
  JSONConfiguration: 'JSON configuration',
  NotDeclared: 'Not declared',
  OverrideCountDescription: 'Variant-specific overrides for {count} {kind}.',
  NoOverridesDescription: 'No overrides. Uses the original {kind}.',
  StepContentChanges: 'Step content changes',
  ResultChanges: 'Result changes',
  Affected: 'Affected',
  ThisVariantInheritsAll: 'This variant inherits all',
  StepContent: 'step content',
  InheritedResultContent: 'result content',
  FromTheOriginalConfiguration: 'from the original configuration.',
  Step: 'Step',
  Of: 'of',
  ContentOverride: 'Content override',
  AnswerOptions: 'Answer options',
  SingleChoiceDescription: 'Participants can choose one answer.',
  SelectionRangeDescription: 'Participants can choose {minimum}–{maximum} answers.',
  OptionsPreviewDescription: 'Read-only preview of the configured options.',
  Value: 'Value',
  StepRulesAndSequence: 'Step rules and sequence',
  Behavior: 'Behavior',
  Required: 'Required',
  Optional: 'Optional',
  ChooseOne: 'Choose one',
  Selections: 'Selections:',
  NumberInput: 'Number input',
  Increment: 'Increment:',
  AnswerField: 'Answer field:',
  RequiredAnswerDescription: 'An answer is required before continuing.',
  OptionalAnswerDescription: 'Participants can continue without an answer.',
  ServerValidationDescription: 'Values are checked by the server.',
  ResultSource: 'Result source:',
  AlwaysVisible: 'Always visible',
  VisibilityRules: 'Visibility rules',
  Conditional: 'Conditional',
  AdvancedInputValidation: 'Advanced input & validation',
  SelectionLimits: 'Selection limits',
  Options: 'options',
  Minimum: 'Minimum',
  Maximum: 'Maximum',
  SelectionLimitsDescription:
    'The range shows how many answers are accepted, not which options are selected.',
  ConfiguredStepSequence: 'Configured step sequence',
  InTheFlow: 'In the flow',
  Previous: 'Previous',
  StartOfFlow: 'Start of flow',
  Current: 'Current',
  Next: 'Next',
  EndOfFlow: 'End of flow',
  SequenceVisibilityDescription: 'configuration order. Visibility rules can skip steps.',
  Information: 'Information',
  SingleChoice: 'Single choice',
  MultipleChoice: 'Multiple choice',
  Result: 'Result',
  OnlyInVariant: 'Only in {variant}',
  AbsentFromVariant: 'Not in variant {variant}',
  SamePosition: 'Same position',
  BothVariantsPosition: 'Both variants · #{position}',
  OnePlaceEarlier: '1 place earlier',
  OnePlaceLater: '1 place later',
  PlacesEarlier: '{count} places earlier',
  PlacesLater: '{count} places later',
  BackToConfigurations: 'Back to configurations',
  Refresh: 'Refresh',
  LoadingConfigurationVersion: 'Loading configuration version',
  ConfigurationCouldNotBeLoaded: 'Configuration could not be loaded',
  TryAgain: 'Try again',
  VersionOverview: 'Version overview',
  Version: 'Version',
  ReadOnly: 'Read-only',
  Published: 'Published',
  Draft: 'Draft',
  TechnicalDetails: 'Technical details',
  VersionIdentifier: 'Version identifier',
  ContentFingerprint: 'Content fingerprint',
  DocumentStatusDescription: 'Document status does not indicate which version is live.',

  positionChange(
    previousVariant: string,
    previousPosition: Optional<number>,
    variant: string,
    position: number,
  ): string {
    return `${previousVariant} #${previousPosition} → ${variant} #${position}`;
  },
} as const;
