// SQL identifiers in the report envelope come only from these authored field lists.
export const AnalyticsReportFields = {
  Summaries: ['versionIdentifier', 'variant', 'started', 'results', 'clicks', 'resultClicks'],
  Steps: [
    'versionIdentifier',
    'variant',
    'stepIdentifier',
    'reached',
    'completed',
    'observedCompleted',
    'expiredReached',
    'openNoncompletion',
    'expiredNoncompletion',
  ],
  Edges: [
    'versionIdentifier',
    'variant',
    'fromStepIdentifier',
    'toStepIdentifier',
    'transitions',
    'sourceCompleted',
    'sourceReached',
    'observed',
    'destinationReached',
    'openNonreach',
    'expiredNonreach',
  ],
  BusinessOutcomes: ['kind', 'sessions', 'manualSessions', 'integrationSessions'],
  Trend: ['date', 'started', 'results', 'clicks'],
  Acquisition: ['source', 'medium', 'campaign', 'started', 'results', 'clicks'],
  Results: ['resultIdentifier', 'sessions', 'clicks'],
  Quality: ['latestEventAt', 'openSessions', 'matureSessions'],
  StepTimings: [
    'versionIdentifier',
    'variant',
    'stepIdentifier',
    'observedSessions',
    'averageSeconds',
  ],
} as const;
