export const AnalyticsCases = {
  Sessions: [
    { sessionIdentifier: 'complete', version: 1 },
    { sessionIdentifier: 'expired', version: 1, expired: true },
    { sessionIdentifier: 'pending', version: 1 },
    { sessionIdentifier: 'abandoned', version: 1, expired: true },
    { sessionIdentifier: 'unobserved', version: 1 },
    { sessionIdentifier: 'forced', version: 1, assignmentSource: 'forced' },
    { sessionIdentifier: 'synthetic', version: 1, trafficOrigin: 'synthetic' },
    { sessionIdentifier: 'other-campaign', version: 1, campaign: 'other', variant: 'B' },
    { sessionIdentifier: 'third', version: 3, variant: 'B' },
    { sessionIdentifier: 'without-start', version: 1, started: false },
  ],
  Views: [
    {
      sessionIdentifier: 'complete',
      stepIdentifiers: [
        'result',
        'office_days',
        'timezone_span',
        'intro',
        'team_size',
        'work_mode',
        'intro',
        'work_mode',
      ],
    },
    { sessionIdentifier: 'expired', stepIdentifiers: ['intro', 'team_size', 'work_mode'] },
    { sessionIdentifier: 'pending', stepIdentifiers: ['intro', 'team_size'] },
    { sessionIdentifier: 'abandoned', stepIdentifiers: ['intro'] },
    { sessionIdentifier: 'unobserved', stepIdentifiers: ['team_size'] },
    { sessionIdentifier: 'without-start', stepIdentifiers: ['intro'] },
  ],
  Transitions: [
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'intro',
      toStepIdentifier: 'team_size',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'team_size',
      toStepIdentifier: 'work_mode',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'work_mode',
      toStepIdentifier: 'timezone_span',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'timezone_span',
      toStepIdentifier: 'work_mode',
      kind: 'back',
    },
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'work_mode',
      toStepIdentifier: 'office_days',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'complete',
      fromStepIdentifier: 'work_mode',
      toStepIdentifier: 'office_days',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'expired',
      fromStepIdentifier: 'intro',
      toStepIdentifier: 'team_size',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'expired',
      fromStepIdentifier: 'team_size',
      toStepIdentifier: 'work_mode',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'expired',
      fromStepIdentifier: 'work_mode',
      toStepIdentifier: 'timezone_span',
      kind: 'forward',
    },
    {
      sessionIdentifier: 'unobserved',
      fromStepIdentifier: 'intro',
      toStepIdentifier: 'team_size',
      kind: 'forward',
    },
  ],
  Outcomes: [
    { sessionIdentifier: 'complete', eventName: 'cta_clicked' },
    { sessionIdentifier: 'complete', eventName: 'result_viewed' },
    { sessionIdentifier: 'complete', eventName: 'result_viewed' },
    { sessionIdentifier: 'expired', eventName: 'cta_clicked' },
  ],
  InvalidQueries: [
    { name: 'missing funnel', query: {} },
    { name: 'empty page', query: { funnelIdentifier: 'workstyle-planner', limit: '0' } },
    { name: 'oversized page', query: { funnelIdentifier: 'workstyle-planner', limit: '21' } },
    { name: 'oversized offset', query: { funnelIdentifier: 'workstyle-planner', offset: '10001' } },
    {
      name: 'invalid version',
      query: { funnelIdentifier: 'workstyle-planner', versionIdentifier: 'not-a-uuid' },
    },
    {
      name: 'unknown field',
      query: { funnelIdentifier: 'workstyle-planner', unexpected: 'value' },
    },
    {
      name: 'invalid forced selector',
      query: { funnelIdentifier: 'workstyle-planner', includeForced: '1' },
    },
    {
      name: 'invalid origin selector',
      query: { funnelIdentifier: 'workstyle-planner', trafficOrigin: 'test' },
    },
    {
      name: 'oversized campaign',
      query: { funnelIdentifier: 'workstyle-planner', campaign: 'x'.repeat(201) },
    },
  ],
} as const;
