export const EnvironmentCases = {
  RejectedAdministrationOrigins: [
    '',
    'null',
    'https://user:secret@example.com',
    'https://example.com/',
    'https://example.com/path',
    'https://example.com?query',
    'ftp://example.com',
    'https://example.com#fragment',
    'https://example.com\n',
  ],
  RejectedProductionOrigins: [undefined, 'http://example.com', 'http://localhost:5173'],

  AcceptedLogLevels: ['trace', 'debug', 'info', 'warn', 'error', 'fatal'],
  RejectedLogLevels: [
    '',
    'INFO',
    'verbose',
    'silent',
    'debug ',
    'info\n',
    'private-log-level-marker',
  ],
  InvalidPorts: ['0', '65536', '3000suffix', '1.5', '-1'],
  UnsupportedDatabaseUrls: ['postgresql://localhost/example', 'file:', 'file:./example?mode=ro'],
  AcceptedModes: ['development', 'test', 'production'],
  AcceptedPorts: ['1', '00001', '65535'],
  MalformedPorts: ['', '000001', ' 3000', '3e3', 'NaN', 'Infinity', '+3000', '3000\n'],
  AcceptedHosts: ['localhost', '::1', 'a'.repeat(253)],
  UnsupportedHosts: ['', 'a'.repeat(254), 'example/path', 'example host', 'localhost\n'],
  UnsafeDatabaseUrls: ['file:./example#fragment', 'file:./example\0', 'file:', 'https://example'],
  AbsoluteDatabaseUrls: ['file:/tmp/kelpie.sqlite', 'file:/tmp/kelpie\n.sqlite'],
} as const;
