export const HealthRequestCases = [
  {
    name: 'rejects oversized bodies without echoing input',
    body: JSON.stringify({ secret: 'x'.repeat(270_000) }),
    headers: {},
    expectedStatus: 413,
    expectedResponse: {
      statusCode: 413,
      code: 'payload_too_large',
      message: 'Request body is too large.',
    },
  },
  {
    name: 'rejects malformed JSON without exposing submitted content',
    body: '{"secret":"private-value",',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects unsupported charsets as input errors',
    body: '{"secret":"private-value"}',
    headers: { 'content-type': 'application/json;charset=iso-8859-1' },
    expectedStatus: 415,
    expectedResponse: {
      statusCode: 415,
      code: 'unsupported_media_type',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects compressed requests before decompression',
    body: 'private-compressed-value',
    headers: { 'content-encoding': 'gzip' },
    expectedStatus: 415,
    expectedResponse: {
      statusCode: 415,
      code: 'unsupported_media_type',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects scalar numbers',
    body: '42',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects scalar strings',
    body: '"private-value"',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects null bodies',
    body: 'null',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects boolean bodies',
    body: 'true',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'accepts object JSON before route resolution',
    body: '{"value":1}',
    headers: {},
    expectedStatus: 404,
    expectedResponse: {
      statusCode: 404,
      code: 'not_found',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'accepts array JSON before route resolution',
    body: '[1,2]',
    headers: {},
    expectedStatus: 404,
    expectedResponse: {
      statusCode: 404,
      code: 'not_found',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'accepts case-insensitive quoted UTF-8 charset',
    body: '{}',
    headers: { 'content-type': 'application/json; charset="UTF-8"' },
    expectedStatus: 404,
    expectedResponse: {
      statusCode: 404,
      code: 'not_found',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'accepts identity content encoding',
    body: '{}',
    headers: { 'content-encoding': 'identity' },
    expectedStatus: 404,
    expectedResponse: {
      statusCode: 404,
      code: 'not_found',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects conflicting duplicate charset parameters',
    body: '{}',
    headers: { 'content-type': 'application/json; charset=utf-8; charset=iso-8859-1' },
    expectedStatus: 415,
    expectedResponse: {
      statusCode: 415,
      code: 'unsupported_media_type',
      message: 'Request could not be processed.',
    },
  },
  {
    name: 'rejects JSON prototype poisoning',
    body: '{"__proto__":{"polluted":true}}',
    headers: {},
    expectedStatus: 400,
    expectedResponse: {
      statusCode: 400,
      code: 'invalid_request',
      message: 'Request could not be processed.',
    },
  },
] as const;
