export const AdministrationContent = {
  Brand: 'kelpie',
  WorkspaceLabel: 'Administration',
  SignInTitle: 'Welcome back',
  SignInDescription: 'Sign in to your workspace to continue.',
  UsernameLabel: 'Username',
  UsernamePlaceholder: 'Your administrator username',
  PasswordLabel: 'Password',
  PasswordPlaceholder: 'Enter your password',
  ShowPassword: 'Show password',
  HidePassword: 'Hide password',
  CapsLock: 'Caps Lock is on',
  SignIn: 'Sign in to workspace',
  SigningIn: 'Signing in…',
  SignInFailed: 'Unable to sign in',
  AccessNote: 'Access is reserved for your team.',
  AccessHelp: 'Contact your administrator for access or a password reset.',
  CheckingTitle: 'Opening your workspace',
  CheckingDescription: 'Checking your administrator session…',
  UnavailableTitle: 'Unable to connect',
  Retry: 'Try again',
  SignedInTitle: 'You’re signed in',
  SignedInDescription: 'Your administrator session is active.',
  SignedInNotice: 'Workspace access confirmed',
  SignedInNoticeDescription: 'Your session has been verified by the Kelpie backend.',
  SignOut: 'Sign out',
  SigningOut: 'Signing out…',
  SignOutFailed: 'Unable to sign out',
  PanelKicker: 'One connected workspace',
  PanelEyebrow: 'LESS NOISE. MORE CLARITY.',
  PanelHeading: 'Everything',
  PanelHeadingAccent: 'in control.',
  PanelDescription: 'Your funnels, processes and insights.',
  PanelDescriptionSecond: 'One place for confident decisions.',
  PanelArtLabel: 'Clarity in every detail.',
  PanelFooter: 'Built for your team',
  PanelStep: '01 — Access',
  CookieNote: 'Server-managed session',
  PageTitle: 'Administration · Kelpie',
} as const;

export const AdministrationFormMessages = {
  UsernameRequired: 'Enter your administrator username.',
  PasswordRequired: 'Enter your password.',
  RequestFailed: 'Unable to complete the request. Please try again.',
} as const;
