export const AdministrationContent = {
  Brand: 'Kelpie',
  WorkspaceLabel: 'Administration',
  SignInTitle: 'Welcome back',
  SignInDescription: 'Sign in to your Kelpie workspace.',
  PanelTitle: 'Every step.\nA clearer picture.',
  PanelDescription:
    'See where people continue, where they leave, and what changes between versions.',
  Eyebrow: 'FLOW ANALYTICS',
  UsernameLabel: 'Username',
  UsernamePlaceholder: 'Your administrator username',
  PasswordLabel: 'Password',
  PasswordPlaceholder: 'Enter your password',
  ShowPassword: 'Show password',
  HidePassword: 'Hide password',
  CapsLock: 'Caps Lock is on',
  SignIn: 'Sign in',
  SigningIn: 'Signing in…',
  SignInFailed: 'Unable to sign in',
  AccessHelp: 'Contact your administrator if you need access.',
  CheckingTitle: 'Opening your workspace',
  CheckingDescription: 'Checking your administrator session…',
  UnavailableTitle: 'Unable to connect',
  Retry: 'Try again',
  SignOut: 'Sign out',
  SigningOut: 'Signing out…',
  SignOutFailed: 'Unable to sign out',
  PageTitle: 'Administration · Kelpie',
} as const;

export const AdministrationFormMessages = {
  UsernameRequired: 'Enter your administrator username.',
  PasswordRequired: 'Enter your password.',
  RequestFailed: 'Unable to complete the request. Please try again.',
} as const;
