export const DatabaseBackupPolicy = {
  ExpectedTables: [
    '_prisma_migrations',
    'Funnel',
    'FunnelVersion',
    'Publication',
    'Session',
    'SessionAnswer',
    'SessionOperation',
    'Event',
    'Administrator',
    'AdministratorSession',
    'SessionTransition',
    'ApplicationSecret',
    'BusinessOutcome',
    'ExperimentPlan',
  ],
  FilePermissions: 0o600,
  DirectoryPermissions: 0o700,
  TemporaryPrefix: '.kelpie-recovery-',
  SnapshotFilename: 'snapshot.sqlite',
  ChecksumAlgorithm: 'sha256',
} as const;
