export const ConfigurationContent = {
  Heading: 'Configurations',
  Highlights: 'Version highlights',
  HighlightsScope: 'Highest versions on this page',
  FunnelContext: 'Funnel overview',
  LastActivation: 'Last activation',
  InspectActive: 'View active version',
  RecentActivity: 'Recent activity',
  ActivationContext: 'Latest publications and rollbacks',
  ViewHistory: 'View activation history',
  VersionSafety:
    'Versions cannot be edited. Publishing affects only new sessions. Existing sessions keep their original configuration.',
  Search: 'Search versions on this page',
  SearchPlaceholder: 'Search by version, schema or checksum…',
  AllStatuses: 'All statuses',
  FilterStatus: 'Filter by status',
  NoMatches: 'No matching versions',
  NoMatchesDescription: 'Try another version, schema or checksum, or clear your filters.',
  ClearFilters: 'Clear filters',
  PageFilterScope: 'Search, filters and sorting apply only to this page.',
  SortVersions: 'Sort by version',
  Library: 'All versions',
  Description: 'Manage versions and choose which one is live.',
  Import: 'Import configuration',
  HistoryHeading: 'Activation history',
  HistoryDescription: 'Review publications and rollbacks for this funnel.',
  Refresh: 'Refresh',
  Retry: 'Try again',
  EmptyTitle: 'No versions yet',
  EmptyDescription: 'Import a JSON configuration to add your first version.',
  HistoryEmptyTitle: 'No activations yet',
  HistoryEmptyDescription: 'Publish a version to add the first entry.',
  Version: 'Version',
  Status: 'Status',
  Schema: 'Schema',
  Checksum: 'Checksum',
  Actions: 'Actions',
  Columns: 'Columns',
  VisibleColumns: 'Visible columns',
  Draft: 'Draft',
  Inactive: 'Inactive',
  Live: 'Live',
  Publish: 'Publish',
  Rollback: 'Roll back',
  CurrentRevision: 'Current revision',
  CurrentVersion: 'Active version',
  NoActiveVersion: 'Not published',
  ListedVersions: 'On this page',
  ActiveVersionDescription: 'Used for new sessions',
  CurrentRevisionDescription: 'Publication and rollback revision',
  ListedVersionsDescription: 'Versions on this page',
  ChooseFile: 'Choose JSON file',
  ReplaceFile: 'Choose another file',
  ReadingFile: 'Reading your configuration…',
  FileReady: 'Ready for server validation',
  FileRequirements: 'JSON configuration · up to 256 KiB',
  Previous: 'Previous',
  Next: 'Next',
  Inspect: 'Details',
  DetailsTitle: 'Version details',
  DetailsDescription: 'Saved version details. These cannot be edited.',
  Identifier: 'Version identifier',
  Funnel: 'Funnel',
  Close: 'Close',
  LoadFailure: 'Unable to load this funnel',
  Revision: 'Revision',
  Action: 'Action',
  Target: 'Activated version',
  PreviousVersion: 'Previous version',
  Time: 'Activated at',
  Publication: 'Publication',
  RollbackAction: 'Rollback',
  ImportTitle: 'Import a configuration',
  ImportDescription:
    'Upload a JSON file. It will be validated and saved as a draft that cannot be edited.',
  File: 'Configuration JSON',
  ImportAction: 'Validate & import',
  ImportPending: 'Importing…',
  ImportComplete: 'Draft ready',
  ImportExisting: 'This version already exists',
  ImportFailure: 'Could not complete import',
  ImportRetry: 'Retry import',
  PublishTitle: 'Publish this version?',
  RollbackTitle: 'Restore the previous version?',
  PublishDescription:
    'New sessions will use this version. Existing sessions keep their original version.',
  RollbackDescription:
    'New sessions will use the previously active version. Existing sessions and analytics stay unchanged.',
  ConfirmPublish: 'Publish version',
  ConfirmRollback: 'Confirm rollback',
  CommandPending: 'Applying change…',
  CommandFailure: 'Change not confirmed',
  UnknownOutcome: 'We could not confirm the change. Retry to check the same request safely.',
  Conflict:
    'This funnel has changed since you opened this dialog. Refresh to review the current revision.',
  Cancel: 'Cancel',
  RefreshReview: 'Refresh & review',
  RetryCommand: 'Retry request',
  StorageFailure:
    'Your browser could not save this operation for a safe retry. This attempt was not sent.',
  CommandConfirmed: 'Change confirmed',
  RecoveryRetained:
    'Your browser could not clear the saved request. If you reload and retry, the same request will be reused safely.',
  Changed: 'Active version updated.',
  ReadFailure: 'Unable to read the selected file.',
  InvalidJson: 'Choose a valid JSON configuration file.',
  FileTooLarge: 'The file is larger than the 256 KiB request limit.',
} as const;
