export const ConfigurationContent = {
  Heading: 'Configurations',
  Highlights: 'Version highlights',
  HighlightsScope: 'Highest versions on this page',
  FunnelContext: 'Funnel context',
  LastActivation: 'Last activation',
  InspectActive: 'Inspect active version',
  RecentActivity: 'Recent activity',
  ActivationContext: 'Latest publications and rollbacks',
  ViewHistory: 'View activation history',
  VersionSafety:
    'Versions are immutable. Publishing changes new sessions only; existing sessions keep their pinned configuration.',
  Search: 'Search versions on this page',
  SearchPlaceholder: 'Search version, schema or checksum…',
  AllStatuses: 'All statuses',
  FilterStatus: 'Filter version status',
  NoMatches: 'No matching versions',
  NoMatchesDescription: 'Try another version, schema or checksum, or clear your filters.',
  ClearFilters: 'Clear filters',
  PageFilterScope: 'Search and sort apply to this page.',
  SortVersions: 'Sort by version',
  Library: 'All versions',
  Description: 'Manage configuration versions and choose the active version.',
  Import: 'Import configuration',
  HistoryHeading: 'Activation history',
  HistoryDescription: 'Review publications and rollbacks for this funnel.',
  Refresh: 'Refresh',
  Retry: 'Try again',
  EmptyTitle: 'No versions yet',
  EmptyDescription: 'Import your first JSON configuration to get started.',
  HistoryEmptyTitle: 'No activations yet',
  HistoryEmptyDescription: 'Publishing a version will create the first entry in this history.',
  Version: 'Version',
  Status: 'Status',
  Schema: 'Schema',
  Checksum: 'Checksum',
  Actions: 'Actions',
  Columns: 'Columns',
  VisibleColumns: 'Visible columns',
  Draft: 'Draft',
  Live: 'Live',
  Publish: 'Publish',
  Rollback: 'Roll back',
  CurrentRevision: 'Current revision',
  CurrentVersion: 'Active version',
  NoActiveVersion: 'Not published',
  ListedVersions: 'On this page',
  ActiveVersionDescription: 'Used for new sessions',
  CurrentRevisionDescription: 'Publication and rollback revision',
  ListedVersionsDescription: 'Versions in this page of results',
  ChooseFile: 'Choose JSON file',
  FileRequirements: 'JSON configuration · up to 256 KiB',
  Previous: 'Previous',
  Next: 'Next',
  Inspect: 'Details',
  DetailsTitle: 'Version details',
  DetailsDescription: 'Immutable metadata returned by the backend.',
  Identifier: 'Version identifier',
  Funnel: 'Funnel',
  Close: 'Close',
  LoadFailure: 'Unable to load this funnel',
  Revision: 'Revision',
  Action: 'Action',
  Target: 'Activated version',
  PreviousVersion: 'Previous version',
  Time: 'Activated at',
  Publication: 'Publication',
  RollbackAction: 'Rollback',
  ImportTitle: 'Import a configuration',
  ImportDescription:
    'Upload a JSON file. The backend validates and stores it as an immutable draft.',
  File: 'Configuration JSON',
  ImportAction: 'Validate & import',
  ImportPending: 'Importing…',
  ImportComplete: 'Draft is ready',
  ImportExisting: 'This version already exists',
  ImportFailure: 'Import could not be completed',
  ImportRetry: 'Retry import',
  PublishTitle: 'Publish this version?',
  RollbackTitle: 'Restore the previous version?',
  PublishDescription:
    'New sessions will use the selected version. Existing sessions keep their pinned version.',
  RollbackDescription:
    'The previous activation becomes live for new sessions. Existing sessions and analytics stay intact.',
  ConfirmPublish: 'Publish version',
  ConfirmRollback: 'Confirm rollback',
  CommandPending: 'Applying change…',
  CommandFailure: 'Change not confirmed',
  UnknownOutcome:
    'The result is unknown. Retry this same operation to confirm it safely; its identifier is preserved.',
  Conflict:
    'This funnel changed since you opened this dialog. Refresh and review the current revision.',
  Cancel: 'Cancel',
  RefreshReview: 'Refresh & review',
  RetryCommand: 'Retry same operation',
  StorageFailure:
    'This browser cannot preserve the operation for a safe retry. No change was sent.',
  CommandConfirmed: 'Change confirmed',
  RecoveryRetained:
    'The browser recovery record could not be cleared. A retry after reloading will reuse this same operation safely.',
  Changed: 'Active version updated. The current state has been refreshed from the server.',
  ReadFailure: 'Unable to read the selected file.',
  InvalidJson: 'Choose a valid JSON configuration file.',
  FileTooLarge: 'The file exceeds the 256 KiB request limit.',
} as const;
